name: Shell Commands

on: [push]

jobs:
  vm-informations:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Commands
        run: |
          hostname -i
          cat /proc/cpuinfo
          free -h
        shell: bash
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash